config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: {
    sessions: "user/auth/sessions"
  }
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope module: :user do
    get "home" => "home#index", as: :user_home
    get "home/timeline" => "home#timeline", as: :user_home_timeline

    post "posts" => "posts#create", as: :user_posts
    delete "posts/:id" => "posts#destroy", as: :user_post_destroy

    post "posts/:id/likes" => "liked_posts#create", as: :user_post_likes
    delete "posts/:id/likes" => "liked_posts#destroy", as: :user_post_unlike

    get "users" => "users#index", as: :user_users

    get "users/:id" => "users#show", as: :user_user
    get "users/:id/timeline" => "users#timeline", as: :user_user_timeline

    post "users/:id/follows" => "following_users#create", as: :user_user_follows
    delete "users/:id/follows" => "following_users#destroy", as: :user_user_unfollow
  end

  # Defines the root path route ("/")
  root to: redirect("/home")
end

app/views/shareds/_follow_button.html.slim
= button_to user_user_follows_path(user), \
    method: has_been_followed ? :delete : :post, \
    class: "btn btn-outline #{has_been_followed ? 'btn-error' : ''}" do
  = has_been_followed ? "フォロー解除" : "フォローする"

app/views/shareds/_loading.html.slim
.text-center.p-4
  span.loading.loading-spinner.text-info

app/views/shareds/_post.html.slim
= turbo_frame_tag post do
  article.list-row.gap-2.pb-2
    = link_to user_user_path(post.user), \
        class: "btn btn-ghost btn-circle avatar", \
        data: { turbo_frame: "_top" } do
      .w-10.rounded-full
        = image_tag post.user.thumbnail_url, alt: post.user.name
    .flex-1
      .flex
        = link_to post.user.name, user_user_path(post.user), \
            class: "font-bold hover:underline", \
            data: { turbo_frame: "_top" }
        .ml-auto.text-gray-400.text-xs
          = post.created_at.strftime("%Y/%m/%d %H:%M")
      p = post.body
      .flex.mt-1.-mx-2
        = button_to user_post_likes_path(post), \
            method: has_been_liked ? :delete : :post, \
            class: "btn btn-ghost btn-xs gap-1 text-gray-400 #{has_been_liked ? 'text-secondary' : ''}" do
          svg[
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2.5"
            stroke="currentColor"
            class="size-[1.2em]"
          ]
            path[
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"
            ]
          = "いいね#{post.liked_users.size > 0 ? " #{post.liked_users.size}件" : '' }"
        - if show_delete_button
          = button_tag "削除する", \
              class: "btn btn-ghost btn-xs gap-1 text-gray-400 ml-auto", \
              onclick: "post_delete_modal__#{post.id}.showModal()"
          dialog id="post_delete_modal__#{post.id}" class="modal"
            .modal-box
              h3.text-lg.font-bold 投稿の削除
              p.py-4 削除した投稿は復元できません。本当に削除しますか？
              .modal-action
                = button_tag "キャンセル", class: "btn", type: "button", \
                    onclick: "post_delete_modal__#{post.id}.close()"
                = button_to user_post_destroy_path(post), method: :delete, class: "btn btn-error", \
                    onclick: "post_delete_modal__#{post.id}.close()" do
                  | 削除する

app/views/shareds/_user.html.slim
= turbo_frame_tag user do
  .flex.items-center.gap-4
    .flex
      = link_to user_user_path(user), \
          class: "btn btn-ghost btn-circle avatar", \
          data: { turbo_frame: "_top" } do
        .w-10.rounded-full
          = image_tag user.thumbnail_url, alt: user.name
      .flex-1.ml-2
        = link_to user.name, user_user_path(user), \
            class: "font-bold hover:underline", \
            data: { turbo_frame: "_top" }
        .flex.text-xs.gap-2.mt-1
          span
            | フォロー数：
            span.font-bold
              = user.followings.size
          span
            | フォロワー数：
            span.font-bold
              = user.followers.size
    - if show_follow_button
      .ml-auto
        = render "shareds/follow_button", user:, has_been_followed: