config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: {
    sessions: "user/auth/sessions"
  }
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope module: :user do
    get "home" => "home#index", as: :user_home
    get "home/timeline" => "home#timeline", as: :user_home_timeline

    post "posts" => "posts#create", as: :user_posts
    delete "posts/:id" => "posts#destroy", as: :user_post_destroy

    post "posts/:id/likes" => "liked_posts#create", as: :user_post_likes
    delete "posts/:id/likes" => "liked_posts#destroy", as: :user_post_unlike

    get "users" => "users#index", as: :user_users

    get "users/:id" => "users#show", as: :user_user
    get "users/:id/timeline" => "users#timeline", as: :user_user_timeline

    post "users/:id/follows" => "following_users#create", as: :user_user_follows
    delete "users/:id/follows" => "following_users#destroy", as: :user_user_unfollow
  end

  # Defines the root path route ("/")
  root to: redirect("/home")
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :recoverable:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :liked_post_relationships,
            class_name: "LikedPost",
            dependent: :destroy

  # いいねした投稿
  has_many :liked_posts,
           through: :liked_post_relationships,
           source: :post

  has_many :following_relationships,
           class_name: "FollowingUser",
           foreign_key: "user_id",
           dependent: :destroy

  has_many :follower_relationships,
           class_name: "FollowingUser",
           foreign_key: "following_user_id",
           dependent: :destroy

  # フォローしているユーザー
  has_many :followings,
           through: :following_relationships,
           source: :following_user

  # フォローされているユーザー
  has_many :followers,
           through: :follower_relationships,
           source: :user

  scope :search_by_keyword, ->(keyword) {
    where("users.name LIKE ?", "%#{keyword}%")
  }

  # ホーム画面用の投稿を取得する
  def home_timeline_posts(top_cursor: nil, bottom_cursor: nil)
    Post.eager_load(:user, :liked_users)
        .where(user: followings).or(Post.where(user: self))
        .order(id: :desc)
        .limit(50)
        .tap do |query|
          query.where!("posts.id > ?", top_cursor) if top_cursor
          query.where!("posts.id < ?", bottom_cursor) if bottom_cursor
        end
  end

  # ユーザー詳細画面用の投稿を取得する
  def timeline_posts(top_cursor: nil, bottom_cursor: nil)
    Post.eager_load(:user, :liked_users)
        .where(user: self)
        .order(id: :desc)
        .limit(50)
        .tap do |query|
          query.where!("posts.id > ?", top_cursor) if top_cursor
          query.where!("posts.id < ?", bottom_cursor) if bottom_cursor
        end
  end

  # 投稿をいいねする
  def like_post(post)
    liked_posts << post
  end

  # 投稿のいいねを解除する
  def unlike_post(post)
    liked_posts.destroy(post)
  end

  def has_been_followed_by?(user)
    followers.include?(user)
  end

  def follow(user)
    followings << user
  end

  def unfollow(user)
    followings.destroy(user)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def index
  end
end

app/controllers/user/application_controller.rb
# frozen_string_literal: true

class User::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/user/following_users_controller.rb
# frozen_string_literal: true

class User::FollowingUsersController < ApplicationController
  before_action :find_user

  def create
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  def destroy
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def render_turbo_stream
      render turbo_stream: [
        turbo_stream.replace(@user, partial: "shareds/user", locals: {
          user: @user,
          show_follow_button: true,
          has_been_followed: @user.has_been_followed_by?(current_user)
        }),
        turbo_stream.replace(current_user, partial: "shareds/user", locals: {
          user: current_user,
          show_follow_button: false,
          has_been_followed: false
        })
      ]
    end
end

app/controllers/user/home_controller.rb
# frozen_string_literal: true

class User::HomeController < User::ApplicationController
  def index
    @posts = current_user.home_timeline_posts
    @top_cursor = @posts.first&.id
    @bottom_cursor = @posts.last&.id
  end

  def timeline
    @posts = current_user.home_timeline_posts(
      top_cursor: params[:top_cursor],
      bottom_cursor: params[:bottom_cursor]
    )
    @top_cursor = next_top_cursor
    @bottom_cursor = next_bottom_cursor

    render_timeline_turbo_stream
  end

  private

    def request_newer_posts?
      params[:top_cursor].present?
    end

    def request_older_posts?
      params[:bottom_cursor].present?
    end

    def next_top_cursor
      if request_newer_posts?
        # 新着取得リクエストの場合、新着投稿があればその投稿IDを、なければ現在のトップカーソルを返す
        @posts.first&.id || params[:top_cursor]
      elsif request_older_posts?
        nil
      else
        @posts.first&.id
      end
    end

    def next_bottom_cursor
      request_newer_posts? ? nil : @posts.last&.id
    end

    def render_timeline_turbo_stream
      turbo_streams = [
        turbo_stream.replace(
          "home_timeline_load_#{request_older_posts? ? "older" : "newer"}",
          partial: "user/home/posts",
          locals: {
            posts: @posts,
            current_user: current_user,
            top_cursor: @top_cursor,
            bottom_cursor: @bottom_cursor
          }
        )
      ]

      if @top_cursor && @top_cursor != params[:top_cursor]
        turbo_streams << turbo_stream.replace(
          "home_timeline_refresh",
          partial: "user/home/refresh_timeline",
          locals: { top_cursor: @top_cursor }
        )
      end

      render turbo_stream: turbo_streams
    end
end

app/controllers/user/liked_posts_controller.rb
# frozen_string_literal: true

class User::LikedPostsController < User::ApplicationController
  before_action :find_post

  def create
    current_user.like_post(@post)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  def destroy
    current_user.unlike_post(@post)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def render_turbo_stream
      render turbo_stream: turbo_stream.replace(@post, partial: "shareds/post", locals: {
        post: @post,
        has_been_liked: @post.has_been_liked_by?(current_user),
        show_delete_button: @post.user == current_user
      })
    end
end

app/controllers/user/posts_controller.rb
# frozen_string_literal: true

class User::PostsController < User::ApplicationController
  def create
    @post = current_user.posts.build(create_params)
    success = @post.save

    respond_to do |format|
      flash_type = success ? :notice : :alert
      flash_message = success ? "投稿に成功しました" : "投稿に失敗しました"
      flash.now[flash_type] = flash_message

      format.html { redirect_to root_path }
      format.turbo_stream { render_create_turbo_stream(success) }
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    success = @post.destroy

    respond_to do |format|
      flash_type = success ? :notice : :alert
      flash_message = success ? "投稿を削除しました" : "投稿の削除に失敗しました"
      flash.now[flash_type] = flash_message

      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_destroy_turbo_stream(success) }
    end
  end

  private

    def create_params
      params.require(:post).permit(:body)
    end

    def render_create_turbo_stream(success)
      status = success ? :created : :unprocessable_entity

      turbo_streams = [
        turbo_stream.update("flash", partial: "layouts/user/alert"),
        turbo_stream.replace("post_form", partial: "layouts/user/post_form", locals: {
          post: success ? Post.new : @post
        })
      ]

      if success
        turbo_streams << turbo_stream.prepend("home_timeline_load_newer", partial: "shareds/post", locals: {
          post: @post,
          has_been_liked: false,
          show_delete_button: true
        })
      end

      render turbo_stream: turbo_streams, status:
    end

    def render_destroy_turbo_stream(success)
      status = success ? :ok : :unprocessable_entity

      turbo_streams = [
        turbo_stream.update("flash", partial: "layouts/user/alert")
      ]
      turbo_streams << turbo_stream.remove("post_#{params[:id]}") if success

      render turbo_stream: turbo_streams, status:
    end
end

app/controllers/user/users_controller.rb
# frozen_string_literal: true

class User::UsersController < User::ApplicationController
  before_action :find_user, only: %i[show timeline]

  def index
    @keyword = params[:q]

    redirect_back fallback_location: user_home_path if @keyword.blank?

    # TODO: ページネーション対応
    @users = User.eager_load(:followings, :followers).search_by_keyword(@keyword)
  end

  def show
    @posts = @user.timeline_posts
    @bottom_cursor = @posts.last&.id
  end

  def timeline
    @posts = @user.timeline_posts(bottom_cursor: params[:bottom_cursor])
    @bottom_cursor = @posts.last&.id

    render turbo_stream: turbo_stream.replace(
      "user_timeline_load_older",
      partial: "user/users/posts",
      locals: {
        posts: @posts,
        current_user: current_user,
        bottom_cursor: @bottom_cursor
      }
    )
  end

  private

    def find_user
      @user = User.find(params[:id])
    end
end

app/views/user/home/_post.html.slim
article.list-row.gap-2.pb-2
  = link_to user_user_path(post.user), class: "btn btn-ghost btn-circle avatar" do
    .w-10.rounded-full
      = image_tag "avatar.svg"
  .flex-1
    .flex
      = link_to post.user.name, user_user_path(post.user), class: "font-bold hover:underline"
      .ml-auto.text-gray-400.text-xs
        = post.created_at.strftime("%Y/%m/%d %H:%M")
    p = post.body
    .mt-1.-mx-2
      - has_been_liked = post.has_been_liked_by?(current_user)
      = button_to user_post_likes_path(post), \
          method: has_been_liked ? :delete : :post, \
          class: "btn btn-ghost btn-xs gap-1 text-gray-400 #{has_been_liked ? 'text-secondary' : ''}" do
        svg[
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="2.5"
          stroke="currentColor"
          class="size-[1.2em]"
        ]
          path[
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"
          ]
        | いいね

app/views/user/home/_posts.html.slim
- if top_cursor.present?
  #home_timeline_load_newer
- posts.each do |post|
  = render "shareds/post", post:, \
      has_been_liked: post.has_been_liked_by?(current_user), \
      show_delete_button: post.user == current_user
- if bottom_cursor.present?
  = turbo_frame_tag "home_timeline_load_older", loading: "lazy", src: user_home_timeline_path(bottom_cursor:)
    = render "shareds/loading"

app/views/user/home/_refresh_timeline.html.slim
= turbo_frame_tag "home_timeline_refresh" do
  = button_to user_home_timeline_path, params: { top_cursor: }, method: :get,
      class: "btn btn-outline btn-sm" do
    svg[
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="size-[1.2em]"
    ]
      path[
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99"
      ]
    | タイムラインを更新

app/views/user/home/index.html.slim
.flex.mb-4
  h1.text-2xl.font-bold
    | ホーム
  .ml-auto
    = render "refresh_timeline", top_cursor: @top_cursor
.card.card-border.bg-base-100.border-base-300.overflow-hidden
  .list
    = render "posts", \
        posts: @posts, \
        current_user: current_user, \
        bottom_cursor: @bottom_cursor, \
        top_cursor: @top_cursor