config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: {
    sessions: "user/auth/sessions"
  }
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope module: :user do
    get "home" => "home#index", as: :user_home
    get "home/timeline" => "home#timeline", as: :user_home_timeline

    post "posts" => "posts#create", as: :user_posts
    delete "posts/:id" => "posts#destroy", as: :user_post_destroy

    post "posts/:id/likes" => "liked_posts#create", as: :user_post_likes
    delete "posts/:id/likes" => "liked_posts#destroy", as: :user_post_unlike

    get "users" => "users#index", as: :user_users

    get "users/:id" => "users#show", as: :user_user
    get "users/:id/timeline" => "users#timeline", as: :user_user_timeline

    post "users/:id/follows" => "following_users#create", as: :user_user_follows
    delete "users/:id/follows" => "following_users#destroy", as: :user_user_unfollow
  end

  # Defines the root path route ("/")
  root to: redirect("/home")
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :recoverable:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :liked_post_relationships,
            class_name: "LikedPost",
            dependent: :destroy

  # いいねした投稿
  has_many :liked_posts,
           through: :liked_post_relationships,
           source: :post

  has_many :following_relationships,
           class_name: "FollowingUser",
           foreign_key: "user_id",
           dependent: :destroy

  has_many :follower_relationships,
           class_name: "FollowingUser",
           foreign_key: "following_user_id",
           dependent: :destroy

  # フォローしているユーザー
  has_many :followings,
           through: :following_relationships,
           source: :following_user

  # フォローされているユーザー
  has_many :followers,
           through: :follower_relationships,
           source: :user

  scope :search_by_keyword, ->(keyword) {
    where("users.name LIKE ?", "%#{keyword}%")
  }

  # ホーム画面用の投稿を取得する
  def home_timeline_posts(top_cursor: nil, bottom_cursor: nil)
    Post.eager_load(:user, :liked_users)
        .where(user: followings).or(Post.where(user: self))
        .order(id: :desc)
        .limit(50)
        .tap do |query|
          query.where!("posts.id > ?", top_cursor) if top_cursor
          query.where!("posts.id < ?", bottom_cursor) if bottom_cursor
        end
  end

  # ユーザー詳細画面用の投稿を取得する
  def timeline_posts(top_cursor: nil, bottom_cursor: nil)
    Post.eager_load(:user, :liked_users)
        .where(user: self)
        .order(id: :desc)
        .limit(50)
        .tap do |query|
          query.where!("posts.id > ?", top_cursor) if top_cursor
          query.where!("posts.id < ?", bottom_cursor) if bottom_cursor
        end
  end

  # 投稿をいいねする
  def like_post(post)
    liked_posts << post
  end

  # 投稿のいいねを解除する
  def unlike_post(post)
    liked_posts.destroy(post)
  end

  def has_been_followed_by?(user)
    followers.include?(user)
  end

  def follow(user)
    followings << user
  end

  def unfollow(user)
    followings.destroy(user)
  end
end

app/controllers/user/application_controller.rb
# frozen_string_literal: true

class User::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/user/following_users_controller.rb
# frozen_string_literal: true

class User::FollowingUsersController < ApplicationController
  before_action :find_user

  def create
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  def destroy
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def render_turbo_stream
      render turbo_stream: [
        turbo_stream.replace(@user, partial: "shareds/user", locals: {
          user: @user,
          show_follow_button: true,
          has_been_followed: @user.has_been_followed_by?(current_user)
        }),
        turbo_stream.replace(current_user, partial: "shareds/user", locals: {
          user: current_user,
          show_follow_button: false,
          has_been_followed: false
        })
      ]
    end
end

app/controllers/user/home_controller.rb
# frozen_string_literal: true

class User::HomeController < User::ApplicationController
  def index
    @posts = current_user.home_timeline_posts
    @top_cursor = @posts.first&.id
    @bottom_cursor = @posts.last&.id
  end

  def timeline
    @posts = current_user.home_timeline_posts(
      top_cursor: params[:top_cursor],
      bottom_cursor: params[:bottom_cursor]
    )
    @top_cursor = next_top_cursor
    @bottom_cursor = next_bottom_cursor

    render_timeline_turbo_stream
  end

  private

    def request_newer_posts?
      params[:top_cursor].present?
    end

    def request_older_posts?
      params[:bottom_cursor].present?
    end

    def next_top_cursor
      if request_newer_posts?
        # 新着取得リクエストの場合、新着投稿があればその投稿IDを、なければ現在のトップカーソルを返す
        @posts.first&.id || params[:top_cursor]
      elsif request_older_posts?
        nil
      else
        @posts.first&.id
      end
    end

    def next_bottom_cursor
      request_newer_posts? ? nil : @posts.last&.id
    end

    def render_timeline_turbo_stream
      turbo_streams = [
        turbo_stream.replace(
          "home_timeline_load_#{request_older_posts? ? "older" : "newer"}",
          partial: "user/home/posts",
          locals: {
            posts: @posts,
            current_user: current_user,
            top_cursor: @top_cursor,
            bottom_cursor: @bottom_cursor
          }
        )
      ]

      if @top_cursor && @top_cursor != params[:top_cursor]
        turbo_streams << turbo_stream.replace(
          "home_timeline_refresh",
          partial: "user/home/refresh_timeline",
          locals: { top_cursor: @top_cursor }
        )
      end

      render turbo_stream: turbo_streams
    end
end

app/controllers/user/liked_posts_controller.rb
# frozen_string_literal: true

class User::LikedPostsController < User::ApplicationController
  before_action :find_post

  def create
    current_user.like_post(@post)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  def destroy
    current_user.unlike_post(@post)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_turbo_stream }
    end
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def render_turbo_stream
      render turbo_stream: turbo_stream.replace(@post, partial: "shareds/post", locals: {
        post: @post,
        has_been_liked: @post.has_been_liked_by?(current_user),
        show_delete_button: @post.user == current_user
      })
    end
end

app/controllers/user/posts_controller.rb
# frozen_string_literal: true

class User::PostsController < User::ApplicationController
  def create
    @post = current_user.posts.build(create_params)
    success = @post.save

    respond_to do |format|
      flash_type = success ? :notice : :alert
      flash_message = success ? "投稿に成功しました" : "投稿に失敗しました"
      flash.now[flash_type] = flash_message

      format.html { redirect_to root_path }
      format.turbo_stream { render_create_turbo_stream(success) }
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    success = @post.destroy

    respond_to do |format|
      flash_type = success ? :notice : :alert
      flash_message = success ? "投稿を削除しました" : "投稿の削除に失敗しました"
      flash.now[flash_type] = flash_message

      format.html { redirect_back(fallback_location: root_path) }
      format.turbo_stream { render_destroy_turbo_stream(success) }
    end
  end

  private

    def create_params
      params.require(:post).permit(:body)
    end

    def render_create_turbo_stream(success)
      status = success ? :created : :unprocessable_entity

      turbo_streams = [
        turbo_stream.update("flash", partial: "layouts/user/alert"),
        turbo_stream.replace("post_form", partial: "layouts/user/post_form", locals: {
          post: success ? Post.new : @post
        })
      ]

      if success
        turbo_streams << turbo_stream.prepend("home_timeline_load_newer", partial: "shareds/post", locals: {
          post: @post,
          has_been_liked: false,
          show_delete_button: true
        })
      end

      render turbo_stream: turbo_streams, status:
    end

    def render_destroy_turbo_stream(success)
      status = success ? :ok : :unprocessable_entity

      turbo_streams = [
        turbo_stream.update("flash", partial: "layouts/user/alert")
      ]
      turbo_streams << turbo_stream.remove("post_#{params[:id]}") if success

      render turbo_stream: turbo_streams, status:
    end
end

app/controllers/user/users_controller.rb
# frozen_string_literal: true

class User::UsersController < User::ApplicationController
  before_action :find_user, only: %i[show timeline]

  def index
    @keyword = params[:q]

    redirect_back fallback_location: user_home_path if @keyword.blank?

    # TODO: ページネーション対応
    @users = User.eager_load(:followings, :followers).search_by_keyword(@keyword)
  end

  def show
    @posts = @user.timeline_posts
    @bottom_cursor = @posts.last&.id
  end

  def timeline
    @posts = @user.timeline_posts(bottom_cursor: params[:bottom_cursor])
    @bottom_cursor = @posts.last&.id

    render turbo_stream: turbo_stream.replace(
      "user_timeline_load_older",
      partial: "user/users/posts",
      locals: {
        posts: @posts,
        current_user: current_user,
        bottom_cursor: @bottom_cursor
      }
    )
  end

  private

    def find_user
      @user = User.find(params[:id])
    end
end

app/views/layouts/user/_alert.html.slim
- if alert || notice
  .toast.toast-end.z-50
    - if notice
      .alert.alert-info.opacity-0.transition-opacity.duration-500[data-controller="alert"]
        span = notice
    - if alert
      .alert.alert-error.opacity-0.transition-opacity.duration-500[data-controller="alert"]
        span = alert
  

app/views/layouts/user/_auth_alert.html.slim
/ Devise alert messages
- if alert
  .alert.alert-error.mb-5[role="alert"]
    svg[
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6 shrink-0 stroke-current"
      fill="none"
      viewBox="0 0 24 24"
    ]
      path[
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
      ]
    span = alert

app/views/layouts/user/_header.html.slim
header.navbar.bg-base-100.shadow-sm.sticky.inset-x-0.top-0.z-50
  .navbar-start
  .navbar-center
    = link_to user_home_path, class: "btn btn-ghost text-xl", data: { turbo_prefetch: false } do
      | Hotwire SNS Sample
  .navbar-end
    - if user_signed_in?
      = form_with url: user_users_path, method: :get, class: "input w-auto mr-4" do
        svg[
          class="h-[1em] opacity-50"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
        ]
          g[stroke-linejoin="round" stroke-linecap="round" stroke-width="2.5" fill="none" stroke="currentColor"]
            circle[cx="11" cy="11" r="8"]
            path[d="m21 21-4.3-4.3"]
        = text_field_tag :q, nil, type: :search, placeholder: "ユーザー検索"
        = button_tag type: :submit, class: "hidden", name: nil
      .dropdown.dropdown-end.mr-2
        .btn.btn-ghost.btn-circle.avatar[tabindex="0" role="button"]
          .w-10.rounded-full
            = image_tag current_user.thumbnail_url, alt: current_user.name
        ul.menu.menu-sm.dropdown-content.bg-base-100.rounded-box.z-1.mt-3.w-52.p-2.shadow[tabindex="0"]
          li.col-span-full
            = button_to destroy_user_session_path, method: "delete", \
                class: "w-full cursor-pointer text-left", \
                form: {class: "block"} do
              | ログアウト

app/views/layouts/user/_post_form.html.slim
#post_form
  = form_with model: post, url: user_posts_path, method: :post do |form|
    fieldset.fieldset
      div
        = form.text_area :body, class: "textarea", placeholder: "最大200文字まで入力できます", rows: 4, required: true
        - error_message = form.object.errors.full_messages_for(:body).first
        - if error_message.present?
          p.validator-hint.text-error = error_message
      = form.submit "投稿する", class: "btn btn-neutral mt-2"

app/views/layouts/user/_sidebar.html.slim
#sidebar[class="flex-none w-[350px]" data-turbo-permanent="true"]
  div class="card card-border bg-base-100 border-base-300 sticky top-[84px] z-20"
    .card-body.p-4
      = render "shareds/user", user: current_user, show_follow_button: false
      = render "layouts/user/post_form", post: Post.new

app/views/layouts/user/application.html.slim
doctype html
html.h-full.bg-neutral-50[data-theme="light"]
  head
    title
      | Hotwire SNS
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.min-h-full.flex.flex-col
    = render 'layouts/user/header'
    main.flex.flex-col.flex-1.py-5
      .container.mx-auto.flex.flex-col.flex-1.px-4
        #flash
          = render "layouts/user/alert"
        .flex.flex-1
          = render 'layouts/user/sidebar'
          .divider.divider-horizontal.mx-6
          .flex-1
            = yield

app/views/layouts/user/auth.html.slim
doctype html
html.bg-neutral-50[data-theme="light"]
  head
    title
      | Hotwire SNS
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render 'layouts/user/header'
    main.py-5
      .container.mx-auto.max-w-sm
        = render "layouts/user/auth_alert"  
        = yield